# Generated by Django 3.2.6 on 2021-08-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_portfolio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.CharField(blank=True, max_length=2558, null=True),
        ),
    ]
